# Generated by Django 5.0.6 on 2024-08-04 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timerange',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='check_start_time_before_end_time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timeRange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timerange'),
        ),
    ]
