# Generated by Django 5.0.6 on 2024-08-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timeRange',
        ),
        migrations.AddField(
            model_name='schedule',
            name='earliest_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='earliest start time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='latest_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='latest end time'),
        ),
        migrations.CreateModel(
            name='TimeRangeUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('owner', models.CharField(max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='timerange',
            name='time_range_union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.timerangeunion'),
        ),
    ]
