# Generated by Django 5.0.6 on 2024-10-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerangeunion',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='SlotCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=200)),
                ('slots', models.JSONField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeRange',
        ),
        migrations.DeleteModel(
            name='TimeRangeUnion',
        ),
    ]
